### ISSUE TITLE
Repair all graphics

### ISSUE THREAD

**Issue by Bazek** [BRTrains/OpenTTE#2]
Hello, I am just working on repairing all graphics. Pip and Ema, are now broken.
And I also want to split all wagons. Annie, Clarabel, Pip, Ema, Toby, Henrietta, Elsie, First class, Second Class, ... to enable buying separrately. What do you think about this? @audigex

**Comment by Bazek** [comment]
Finally I made it. It just waits for your review and merge and release.

**Comment by Bazek** [comment]
Hello, @audigex, Is there any progress here? Can I publish my version of grf to OpenTTD bananas servers? I am just waiting for your approvement.

**Comment by audigex** [comment]
Hi @Bazek sorry, I had no idea anyone else was even working on this, and for some reason I haven't had emails notifying me about the replies here

Are you on TT-Forums? Drop me a PM (same username as here) and we can discuss further

**Comment by audigex** [comment]
Changes merged and released, thanks! And apologies again for the delay, I wish I'd noticed this back in November/December
